spring:
  application:
    name: chat
  ai:
    openai:
      base-url: https://api.crond.dev
      api-key: "sk-lG4mofdU8BGIgnd7CqACxOn5uWXepwMLrl8OZuAhpTvPSvzC"
      chat:
        options:
          model: gpt-4o-mini
    ollama:
      base-url: http://localhost:11434
      chat:
        model: qwen2.5-coder:7b-instruct