spring:
  application:
    name: chat
  ai:
    openai:
      base-url: https://one-api.touchfishes.com
      api-key: "sk-l32cyNTDizg8pmV7RcQ2glwx5b01278FQBXbR4Xi86jwlCEK"
      chat:
        options:
          model: gpt-4o-mini
    ollama:
      base-url: http://localhost:11434
      chat:
        model: qwen2.5-coder:7b-instruct